version: "3.9"

services:
  keycloakapp:
    image: quay.io/keycloak/keycloak:25.0.2
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 8075:8080